const Testdata = {
  login: "bchiang7",
  id: 6599979,
  node_id: "MDQ6VXNlcjY1OTk5Nzk=",
  avatar_url: "https://avatars.githubusercontent.com/u/6599979?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/bchiang7",
  html_url: "https://github.com/bchiang7",
  followers_url: "https://api.github.com/users/bchiang7/followers",
  following_url: "https://api.github.com/users/bchiang7/following{/other_user}",
  gists_url: "https://api.github.com/users/bchiang7/gists{/gist_id}",
  starred_url: "https://api.github.com/users/bchiang7/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/bchiang7/subscriptions",
  organizations_url: "https://api.github.com/users/bchiang7/orgs",
  repos_url: "https://api.github.com/users/bchiang7/repos",
  events_url: "https://api.github.com/users/bchiang7/events{/privacy}",
  received_events_url: "https://api.github.com/users/bchiang7/received_events",
  type: "User",
  site_admin: false,
  name: "Brittany Chiang",
  company: "@Upstatement ",
  blog: "https://brittanychiang.com",
  location: "Boston, MA",
  email: null,
  hireable: true,
  bio: null,
  twitter_username: "bchiang7",
  public_repos: 63,
  public_gists: 26,
  followers: 5478,
  following: 13,
  created_at: "2014-02-05T23:22:59Z",
  updated_at: "2022-07-20T22:52:21Z",
};

export default Testdata;
